clc; clear; close all;
mdl_puma560

% 1. 设定起始和终止关节角
q_start = qz;
q_end   = qr;

% 2. 在关节空间中进行轨迹规划
n = 50;
[q, qd, qdd] = jtraj(q_start, q_end, n);

% 3. 用正运动学计算每个时刻的末端位姿
Ts = repmat(eye(4), 1, 1, n);
xyz = zeros(n, 3);

for i = 1:n
    Ts(:,:,i) = p560.fkine(q(i,:));
    xyz(i,:) = transl(Ts(:,:,i));
end

% 4. 对末端位姿做逆运动学，恢复关节角
q_ik = zeros(n, 6);
for i = 1:n
    q_ik(i,:) = p560.ikine6s(Ts(:,:,i));
end

% 5. 计算关节恢复误差
q_err = atan2(sin(q - q_ik), cos(q - q_ik));

% 6. 动画
figure;
p560.plot(q);
title('Joint-space trajectory');

% 7. 末端轨迹图
figure;
plot3(xyz(:,1), xyz(:,2), xyz(:,3), 'LineWidth', 1.5);
grid on; axis equal;
xlabel('X'); ylabel('Y'); zlabel('Z');
title('End-effector trajectory generated by joint-space planning');

% 8. 关节角曲线
figure;
plot(q, 'LineWidth', 1.2);
grid on;
xlabel('Point index');
ylabel('Joint angle (rad)');
title('Joint angles');
legend('q1','q2','q3','q4','q5','q6');

% 9. 关节速度曲线
figure;
plot(qd, 'LineWidth', 1.2);
grid on;
xlabel('Point index');
ylabel('Joint velocity (rad/s)');
title('Joint velocities');
legend('dq1','dq2','dq3','dq4','dq5','dq6');

% 10. 关节加速度曲线
figure;
plot(qdd, 'LineWidth', 1.2);
grid on;
xlabel('Point index');
ylabel('Joint acceleration (rad/s^2)');
title('Joint accelerations');
legend('ddq1','ddq2','ddq3','ddq4','ddq5','ddq6');

% 11. 逆运动学误差图
figure;
plot(q_err, 'LineWidth', 1.2);
grid on;
xlabel('Point index');
ylabel('Joint error (rad)');
title('Inverse kinematics recovery error');
legend('e1','e2','e3','e4','e5','e6');

% 12. 输出最大误差
disp('各关节最大恢复误差(rad)：');
disp(max(abs(q_err), [], 1));